version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: dbName
      MYSQL_USER: mark
      MYSQL_PASSWORD: sbux
      MYSQL_ROOT_PASSWORD: example